// UI Element References for Manga Translator Studio
// Sử dụng getter để tránh query DOM quá sớm (trước khi DOM sẵn sàng)
export const elements = {
    get autoFitRuler() { return document.getElementById('auto-fit-ruler'); },
    get pagesEmptyState() { return document.getElementById('pages-empty-state'); },
    get pagesList() { return document.getElementById('pages-list'); },
    get pageCountBadge() { return document.getElementById('page-count-badge'); },
    get sourceLangSelect() { return document.getElementById('source-lang-select'); },
    get targetLangSelect() { return document.getElementById('target-lang-select'); },
    get pronounMatrixInput() { return document.getElementById('pronoun-matrix-input'); },
    get ocrEnhanceChk() { return document.getElementById('ocr-enhance-chk'); },
    get workspaceEmptyState() { return document.getElementById('workspace-empty-state'); },
    get mangaCanvasContainer() { return document.getElementById('manga-canvas-container'); },
    get mangaBgImage() { return document.getElementById('manga-bg-image'); },
    get mangaOverlaysContainer() { return document.getElementById('manga-overlays-container'); },
    get canvasFloatingToolbar() { return document.getElementById('canvas-floating-toolbar'); },
    get lblFloatingDir() { return document.getElementById('lbl-floating-dir'); },
    get workspaceViewport() { return document.getElementById('workspace-viewport'); },
    get zoomIndicator() { return document.getElementById('zoom-indicator'); },
    get backgroundTaskBar() { return document.getElementById('background-task-bar'); },
    get sidebarPanel() { return document.getElementById('sidebar-panel'); },

    // Edit Panel
    get noBlockSelectedState() { return document.getElementById('no-block-selected-state'); },
    get blockEditorContainer() { return document.getElementById('block-editor-container'); },
    get editOriginalText() { return document.getElementById('edit-original-text'); },
    get editTranslatedText() { return document.getElementById('edit-translated-text'); },
    get lblBlockId() { return document.getElementById('lbl-block-id'); },

    // Tab Containers
    get tabEdit() { return document.getElementById('tab-edit'); },
    get tabStyle() { return document.getElementById('tab-style'); },
    get panelTabEdit() { return document.getElementById('panel-tab-edit'); },
    get panelTabStyle() { return document.getElementById('panel-tab-style'); },

    // Styling Controls
    get styleFont() { return document.getElementById('style-font'); },
    get styleFontSize() { return document.getElementById('style-font-size'); },
    get styleFontSizeContainer() { return document.getElementById('style-font-size-container'); },
    get lblFontSize() { return document.getElementById('lbl-font-size'); },
    get styleAlign() { return document.getElementById('style-align'); },
    get btnStyleHoriz() { return document.getElementById('btn-style-horiz'); },
    get btnStyleVert() { return document.getElementById('btn-style-vert'); },
    get styleBold() { return document.getElementById('style-bold'); },
    get styleTextColor() { return document.getElementById('style-text-color'); },
    get styleTextColorHex() { return document.getElementById('style-text-color-hex'); },
    get styleBgColor() { return document.getElementById('style-bg-color'); },
    get styleBgColorHex() { return document.getElementById('style-bg-color-hex'); },
    get styleBgOpacity() { return document.getElementById('style-bg-opacity'); },
    get lblBgOpacity() { return document.getElementById('lbl-bg-opacity'); },
    get stylePadding() { return document.getElementById('style-padding'); },
    get lblPadding() { return document.getElementById('lbl-padding'); },
    get styleRotate() { return document.getElementById('style-rotate'); },
    get lblRotate() { return document.getElementById('lbl-rotate'); },
    get styleAutoFit() { return document.getElementById('style-auto-fit'); },
    get styleMaskShape() { return document.getElementById('style-mask-shape'); },
    get styleMaskSize() { return document.getElementById('style-mask-size'); },
    get styleStrokeColor() { return document.getElementById('style-stroke-color'); },
    get styleStrokeColorHex() { return document.getElementById('style-stroke-color-hex'); },
    get styleStrokeWidth() { return document.getElementById('style-stroke-width'); },
    get lblStrokeWidth() { return document.getElementById('lbl-stroke-width'); },
    get styleShadowColor() { return document.getElementById('style-shadow-color'); },
    get styleShadowColorHex() { return document.getElementById('style-shadow-color-hex'); },
    get styleShadowBlur() { return document.getElementById('style-shadow-blur'); },
    get lblShadowBlur() { return document.getElementById('lbl-shadow-blur'); },
    get customModelInput() { return document.getElementById('custom-model-input'); },

    // Modals & General Tools
    get processingOverlay() { return document.getElementById('processing-overlay'); },
    get processingTitle() { return document.getElementById('processing-title'); },
    get processingSubtitle() { return document.getElementById('processing-subtitle'); },
    get processingBar() { return document.getElementById('processing-bar'); },
    get toastContainer() { return document.getElementById('toast-container'); },
    get exportModal() { return document.getElementById('export-modal'); },
    get settingsModal() { return document.getElementById('settings-modal'); },
    get settingsModalBody() { return document.getElementById('settings-modal-body'); },
    get exportPreviewImg() { return document.getElementById('export-preview-img'); },
    get lnkExportDirectDownload() { return document.getElementById('lnk-export-direct-download'); },
    get apiKeyInput() { return document.getElementById('api-key-input'); },

    // Splitting Views
    get workspaceSplitWrapper() { return document.getElementById('workspace-split-wrapper'); },
    get splitOriginalImg() { return document.getElementById('split-original-img'); },
    get splitEditorAnchor() { return document.getElementById('split-editor-anchor'); },

    // Trigger Buttons
    get btnActiveTranslate() { return document.getElementById('btn-active-translate'); },
    get btnBatchTranslate() { return document.getElementById('btn-batch-translate'); },
    get btnBatchExport() { return document.getElementById('btn-batch-export'); },
    get btnExportPdf() { return document.getElementById('btn-export-pdf'); },
    get btnExportProject() { return document.getElementById('btn-export-project'); },
    get btnImportProject() { return document.getElementById('btn-import-project'); },
    get btnClearMemory() { return document.getElementById('btn-clear-memory'); },
    get btnExportPage() { return document.getElementById('btn-export-page'); },
    get btnUndo() { return document.getElementById('btn-undo'); },
    get btnRedo() { return document.getElementById('btn-redo'); },
    get btnEraserMode() { return document.getElementById('btn-eraser-mode'); },
    get eraserSettingsPanel() { return document.getElementById('eraser-settings-panel'); },
    get eraserCanvas() { return document.getElementById('eraser-canvas'); },
    get eraserBrushSize() { return document.getElementById('eraser-brush-size'); },
    get lblEraserBrushSize() { return document.getElementById('lbl-eraser-brush-size'); },
    get eraserColorCustom() { return document.getElementById('eraser-color-custom'); },
    get btnExportScript() { return document.getElementById('btn-export-script'); },
    get btnImportScript() { return document.getElementById('btn-import-script'); },
    get btnPreviewMode() { return document.getElementById('btn-preview-mode'); },
    get btnCopyStyle() { return document.getElementById('btn-copy-style'); },
    get btnPasteStyle() { return document.getElementById('btn-paste-style'); },
    get previewModal() { return document.getElementById('preview-modal'); },
    get previewBody() { return document.getElementById('preview-body'); },
    get previewPageIndicator() { return document.getElementById('preview-page-indicator'); },

    // Translation intelligence controls
    get genrePresetOptions() { return document.querySelectorAll('.genre-preset-option'); },
    get consistencyCheckSummary() { return document.getElementById('consistency-check-summary'); },
    get consistencyCheckResults() { return document.getElementById('consistency-check-results'); },

    // TOEIC Study Companion elements
    get tabToeic() { return document.getElementById('tab-toeic'); },
    get panelTabToeic() { return document.getElementById('panel-tab-toeic'); },
    get toeicNoBlockSelectedState() { return document.getElementById('toeic-no-block-selected-state'); },
    get toeicAnalysisContainer() { return document.getElementById('toeic-analysis-container'); },
    get btnToeicAnalyze() { return document.getElementById('btn-toeic-analyze'); },
    get toeicLoading() { return document.getElementById('toeic-loading'); },
    get toeicResults() { return document.getElementById('toeic-results'); },
    get toeicGrammarContent() { return document.getElementById('toeic-grammar-content'); },
    get toeicVocabList() { return document.getElementById('toeic-vocab-list'); },
    get toeicQuestionSection() { return document.getElementById('toeic-question-section'); },
    get toeicQuestionText() { return document.getElementById('toeic-question-text'); },
    get toeicQuestionOptions() { return document.getElementById('toeic-question-options'); },
    get toeicQuestionFeedback() { return document.getElementById('toeic-question-feedback'); },
    get toeicSavedCount() { return document.getElementById('toeic-saved-count'); },
    get btnToeicExportAnki() { return document.getElementById('btn-toeic-export-anki'); },
    get toeicNotebookEmpty() { return document.getElementById('toeic-notebook-empty'); },
    get toeicNotebookList() { return document.getElementById('toeic-notebook-list'); },
    get toeicOriginalSentence() { return document.getElementById('toeic-original-sentence'); },
    get btnSpeakOriginal() { return document.getElementById('btn-speak-original'); },
    get btnSpeakQuestion() { return document.getElementById('btn-speak-question'); },
    get toeicQuestionType() { return document.getElementById('toeic-question-type'); },

    // Active Recall elements
    get toeicLearnModeContent() { return document.getElementById('toeic-learn-mode-content'); },
    get toeicRecallContainer() { return document.getElementById('toeic-recall-container'); },
    get toeicRecallVietnamese() { return document.getElementById('toeic-recall-vietnamese'); },
    get toeicRecallInput() { return document.getElementById('toeic-recall-input'); },
    get toeicRecallResult() { return document.getElementById('toeic-recall-result'); },
    get btnToeicModeLearn() { return document.getElementById('btn-toeic-mode-learn'); },
    get btnToeicModeRecall() { return document.getElementById('btn-toeic-mode-recall'); }
};
