// UI Element References for Manga Translator Studio
// Sử dụng getter để tránh query DOM quá sớm (trước khi DOM sẵn sàng)

export const elements = {
    get autoFitRuler() { return document.getElementById('auto-fit-ruler') as HTMLElement | null; },
    get pagesEmptyState() { return document.getElementById('pages-empty-state') as HTMLElement | null; },
    get pagesList() { return document.getElementById('pages-list') as HTMLElement | null; },
    get pageCountBadge() { return document.getElementById('page-count-badge') as HTMLElement | null; },
    get sourceLangSelect() { return document.getElementById('source-lang-select') as HTMLSelectElement | null; },
    get targetLangSelect() { return document.getElementById('target-lang-select') as HTMLSelectElement | null; },
    get contextPromptInput() { return document.getElementById('translation-context-prompt') as HTMLTextAreaElement | null; },
    get pronounMatrixInput() { return document.getElementById('pronoun-matrix-input') as HTMLTextAreaElement | null; },
    get ocrEnhanceChk() { return document.getElementById('ocr-enhance-chk') as HTMLInputElement | null; },
    get workspaceEmptyState() { return document.getElementById('workspace-empty-state') as HTMLElement | null; },
    get mangaCanvasContainer() { return document.getElementById('manga-canvas-container') as HTMLElement | null; },
    get mangaCanvas() { return document.getElementById('manga-canvas') as HTMLCanvasElement | null; },
    get mangaBgImage() { return document.getElementById('manga-bg-image') as HTMLImageElement | null; },
    get mangaOverlaysContainer() { return document.getElementById('manga-overlays-container') as HTMLElement | null; },
    get canvasFloatingToolbar() { return document.getElementById('canvas-floating-toolbar') as HTMLElement | null; },
    get lblFloatingDir() { return document.getElementById('lbl-floating-dir') as HTMLElement | null; },
    get btnMagicWand() { return document.getElementById('btn-magic-wand') as HTMLButtonElement | null; },
    get magicWandHighlightBox() { return document.getElementById('magic-wand-highlight-box') as HTMLElement | null; },
    get workspaceViewport() { return document.getElementById('workspace-viewport') as HTMLElement | null; },
    get zoomIndicator() { return document.getElementById('zoom-indicator') as HTMLElement | null; },
    get backgroundTaskBar() { return document.getElementById('background-task-bar') as HTMLElement | null; },
    get sidebarPanel() { return document.getElementById('sidebar-panel') as HTMLElement | null; },

    // Edit Panel
    get noBlockSelectedState() { return document.getElementById('no-block-selected-state') as HTMLElement | null; },
    get blockEditorContainer() { return document.getElementById('block-editor-container') as HTMLElement | null; },
    get editOriginalText() { return document.getElementById('edit-original-text') as HTMLTextAreaElement | null; },
    get editTranslatedText() { return document.getElementById('edit-translated-text') as HTMLTextAreaElement | null; },
    get lblBlockId() { return document.getElementById('lbl-block-id') as HTMLElement | null; },
    get inputAddImageBlock() { return document.getElementById('input-add-image-block') as HTMLInputElement | null; },
    get inputReplaceImageBlock() { return document.getElementById('input-replace-image-block') as HTMLInputElement | null; },
    get imageControlsContainer() { return document.getElementById('image-controls-container') as HTMLElement | null; },
    get imgBlockPreview() { return document.getElementById('img-block-preview') as HTMLImageElement | null; },
    get sliderImageOpacity() { return document.getElementById('slider-image-opacity') as HTMLInputElement | null; },
    get lblImageOpacity() { return document.getElementById('lbl-image-opacity') as HTMLElement | null; },
    get selectImageFit() { return document.getElementById('select-image-fit') as HTMLSelectElement | null; },
    get sliderImageBorderRadius() { return document.getElementById('slider-image-border-radius') as HTMLInputElement | null; },
    get lblImageBorderRadius() { return document.getElementById('lbl-image-border-radius') as HTMLElement | null; },

    // Tab Containers
    get tabEdit() { return document.getElementById('tab-edit') as HTMLElement | null; },
    get tabStyle() { return document.getElementById('tab-style') as HTMLElement | null; },
    get panelTabEdit() { return document.getElementById('panel-tab-edit') as HTMLElement | null; },
    get panelTabStyle() { return document.getElementById('panel-tab-style') as HTMLElement | null; },

    // Styling Controls
    get styleFont() { return document.getElementById('style-font') as HTMLSelectElement | null; },
    get styleFontSize() { return document.getElementById('style-font-size') as HTMLInputElement | null; },
    get styleFontSizeContainer() { return document.getElementById('style-font-size-container') as HTMLElement | null; },
    get lblFontSize() { return document.getElementById('lbl-font-size') as HTMLElement | null; },
    get styleAlign() { return document.getElementById('style-align') as HTMLSelectElement | null; },
    get btnStyleHoriz() { return document.getElementById('btn-style-horiz') as HTMLButtonElement | null; },
    get btnStyleVert() { return document.getElementById('btn-style-vert') as HTMLButtonElement | null; },
    get styleBold() { return document.getElementById('style-bold') as HTMLInputElement | null; },
    get styleTextColor() { return document.getElementById('style-text-color') as HTMLInputElement | null; },
    get styleTextColorHex() { return document.getElementById('style-text-color-hex') as HTMLInputElement | null; },
    get styleBgColor() { return document.getElementById('style-bg-color') as HTMLInputElement | null; },
    get styleBgColorHex() { return document.getElementById('style-bg-color-hex') as HTMLInputElement | null; },
    get styleBgOpacity() { return document.getElementById('style-bg-opacity') as HTMLInputElement | null; },
    get lblBgOpacity() { return document.getElementById('lbl-bg-opacity') as HTMLElement | null; },
    get stylePadding() { return document.getElementById('style-padding') as HTMLInputElement | null; },
    get lblPadding() { return document.getElementById('lbl-padding') as HTMLElement | null; },
    get styleRotate() { return document.getElementById('style-rotate') as HTMLInputElement | null; },
    get lblRotate() { return document.getElementById('lbl-rotate') as HTMLElement | null; },
    get styleAutoFit() { return document.getElementById('style-auto-fit') as HTMLInputElement | null; },
    get styleMaskShape() { return document.getElementById('style-mask-shape') as HTMLSelectElement | null; },
    get styleMaskSize() { return document.getElementById('style-mask-size') as HTMLSelectElement | null; },
    get styleStrokeColor() { return document.getElementById('style-stroke-color') as HTMLInputElement | null; },
    get styleStrokeColorHex() { return document.getElementById('style-stroke-color-hex') as HTMLInputElement | null; },
    get styleStrokeWidth() { return document.getElementById('style-stroke-width') as HTMLInputElement | null; },
    get lblStrokeWidth() { return document.getElementById('lbl-stroke-width') as HTMLElement | null; },
    get styleShadowColor() { return document.getElementById('style-shadow-color') as HTMLInputElement | null; },
    get styleShadowColorHex() { return document.getElementById('style-shadow-color-hex') as HTMLInputElement | null; },
    get styleShadowBlur() { return document.getElementById('style-shadow-blur') as HTMLInputElement | null; },
    get lblShadowBlur() { return document.getElementById('lbl-shadow-blur') as HTMLElement | null; },
    get customModelInput() { return document.getElementById('custom-model-input') as HTMLInputElement | null; },

    // Modals & General Tools
    get processingOverlay() { return document.getElementById('processing-overlay') as HTMLElement | null; },
    get processingTitle() { return document.getElementById('processing-title') as HTMLElement | null; },
    get processingSubtitle() { return document.getElementById('processing-subtitle') as HTMLElement | null; },
    get processingBar() { return document.getElementById('processing-bar') as HTMLElement | null; },
    get toastContainer() { return document.getElementById('toast-container') as HTMLElement | null; },
    get exportModal() { return document.getElementById('export-modal') as HTMLElement | null; },
    get settingsModal() { return document.getElementById('settings-modal') as HTMLElement | null; },
    get settingsModalBody() { return document.getElementById('settings-modal-body') as HTMLElement | null; },
    get uiLangSelect() { return document.getElementById('ui-lang-select') as HTMLSelectElement | null; },
    get exportPreviewImg() { return document.getElementById('export-preview-img') as HTMLImageElement | null; },
    get lnkExportDirectDownload() { return document.getElementById('lnk-export-direct-download') as HTMLAnchorElement | null; },
    get apiKeyInput() { return document.getElementById('api-key-input') as HTMLInputElement | null; },

    // Splitting Views
    get workspaceSplitWrapper() { return document.getElementById('workspace-split-wrapper') as HTMLElement | null; },
    get splitOriginalImg() { return document.getElementById('split-original-img') as HTMLImageElement | null; },
    get splitEditorAnchor() { return document.getElementById('split-editor-anchor') as HTMLElement | null; },

    // Trigger Buttons
    get btnActiveTranslate() { return document.getElementById('btn-active-translate') as HTMLButtonElement | null; },
    get btnAiErasePage() { return document.getElementById('btn-ai-erase-page') as HTMLButtonElement | null; },
    get btnBatchTranslate() { return document.getElementById('btn-batch-translate') as HTMLButtonElement | null; },
    get btnBatchExport() { return document.getElementById('btn-batch-export') as HTMLButtonElement | null; },
    get btnExportPdf() { return document.getElementById('btn-export-pdf') as HTMLButtonElement | null; },
    get btnExportProject() { return document.getElementById('btn-export-project') as HTMLButtonElement | null; },
    get btnImportProject() { return document.getElementById('btn-import-project') as HTMLButtonElement | null; },
    get btnClearMemory() { return document.getElementById('btn-clear-memory') as HTMLButtonElement | null; },
    get btnExportPage() { return document.getElementById('btn-export-page') as HTMLButtonElement | null; },
    get btnUndo() { return document.getElementById('btn-undo') as HTMLButtonElement | null; },
    get btnRedo() { return document.getElementById('btn-redo') as HTMLButtonElement | null; },
    get btnEraserMode() { return (document.getElementById('btn-eraser-mode-floating') || document.getElementById('btn-eraser-mode')) as HTMLButtonElement | null; },
    get eraserSettingsPanel() { return document.getElementById('eraser-settings-panel') as HTMLElement | null; },
    get eraserCanvas() { return document.getElementById('eraser-canvas') as HTMLCanvasElement | null; },
    get eraserBrushSize() { return document.getElementById('eraser-brush-size') as HTMLInputElement | null; },
    get lblEraserBrushSize() { return document.getElementById('lbl-eraser-brush-size') as HTMLElement | null; },
    get eraserColorCustom() { return document.getElementById('eraser-color-custom') as HTMLInputElement | null; },
    get patchPreviewCanvas() { return document.getElementById('patch-preview-canvas') as HTMLCanvasElement | null; },
    get btnExportScript() { return document.getElementById('btn-export-script') as HTMLButtonElement | null; },
    get btnImportScript() { return document.getElementById('btn-import-script') as HTMLButtonElement | null; },
    get btnPreviewMode() { return document.getElementById('btn-preview-mode') as HTMLButtonElement | null; },
    get btnCopyStyle() { return document.getElementById('btn-copy-style') as HTMLButtonElement | null; },
    get btnPasteStyle() { return document.getElementById('btn-paste-style') as HTMLButtonElement | null; },
    get previewModal() { return document.getElementById('preview-modal') as HTMLElement | null; },
    get previewBody() { return document.getElementById('preview-body') as HTMLElement | null; },
    get previewPageIndicator() { return document.getElementById('preview-page-indicator') as HTMLElement | null; },

    // Translation intelligence controls
    get genrePresetOptions() { return document.querySelectorAll('.genre-preset-option') as NodeListOf<HTMLElement>; },
    get consistencyCheckSummary() { return document.getElementById('consistency-check-summary') as HTMLElement | null; },
    get consistencyCheckResults() { return document.getElementById('consistency-check-results') as HTMLElement | null; },

    // TOEIC Study Companion elements
    get tabToeic() { return document.getElementById('tab-toeic') as HTMLElement | null; },
    get panelTabToeic() { return document.getElementById('panel-tab-toeic') as HTMLElement | null; },
    get toeicNoBlockSelectedState() { return document.getElementById('toeic-no-block-selected-state') as HTMLElement | null; },
    get toeicAnalysisContainer() { return document.getElementById('toeic-analysis-container') as HTMLElement | null; },
    get btnToeicAnalyze() { return document.getElementById('btn-toeic-analyze') as HTMLButtonElement | null; },
    get toeicLoading() { return document.getElementById('toeic-loading') as HTMLElement | null; },
    get toeicResults() { return document.getElementById('toeic-results') as HTMLElement | null; },
    get toeicGrammarContent() { return document.getElementById('toeic-grammar-content') as HTMLElement | null; },
    get toeicVocabList() { return document.getElementById('toeic-vocab-list') as HTMLElement | null; },
    get toeicQuestionSection() { return document.getElementById('toeic-question-section') as HTMLElement | null; },
    get toeicQuestionText() { return document.getElementById('toeic-question-text') as HTMLElement | null; },
    get toeicQuestionOptions() { return document.getElementById('toeic-question-options') as HTMLElement | null; },
    get toeicQuestionFeedback() { return document.getElementById('toeic-question-feedback') as HTMLElement | null; },
    get toeicSavedCount() { return document.getElementById('toeic-saved-count') as HTMLElement | null; },
    get btnToeicExportAnki() { return document.getElementById('btn-toeic-export-anki') as HTMLButtonElement | null; },
    get toeicNotebookEmpty() { return document.getElementById('toeic-notebook-empty') as HTMLElement | null; },
    get toeicNotebookList() { return document.getElementById('toeic-notebook-list') as HTMLElement | null; },
    get toeicOriginalSentence() { return document.getElementById('toeic-original-sentence') as HTMLElement | null; },
    get btnSpeakOriginal() { return document.getElementById('btn-speak-original') as HTMLButtonElement | null; },
    get btnSpeakQuestion() { return document.getElementById('btn-speak-question') as HTMLButtonElement | null; },
    get toeicQuestionType() { return document.getElementById('toeic-question-type') as HTMLElement | null; },

    // Active Recall elements
    get toeicLearnModeContent() { return document.getElementById('toeic-learn-mode-content') as HTMLElement | null; },
    get toeicRecallContainer() { return document.getElementById('toeic-recall-container') as HTMLElement | null; },
    get toeicRecallVietnamese() { return document.getElementById('toeic-recall-vietnamese') as HTMLElement | null; },
    get toeicRecallInput() { return document.getElementById('toeic-recall-input') as HTMLInputElement | null; },
    get toeicRecallResult() { return document.getElementById('toeic-recall-result') as HTMLElement | null; },
    get btnToeicModeLearn() { return document.getElementById('btn-toeic-mode-learn') as HTMLButtonElement | null; },
    get btnToeicModeRecall() { return document.getElementById('btn-toeic-mode-recall') as HTMLButtonElement | null; }
};
