/**
 * Centralized Global Bridge for HTML Inline Event Handlers
 * 
 * NOTE: This is the ONLY place in the codebase where functions are bound to `window`
 * for backward compatibility with static HTML onclick/onchange attributes.
 * All feature modules must remain pure and free of window mutations.
 */

import * as io from '../features/io';
import * as gdrive from '../features/gdrive';
import * as audio from '../features/audio';
import * as toeic from '../features/toeic';
import * as pronoun from '../features/pronoun';
import * as fsAccess from '../features/fs-access';
import * as inpainting from '../features/inpainting';
import * as canvasService from '../features/canvas/canvas-service';
import * as aiService from '../features/ai/ai-service';
import { toggleMobileHandMode, isMobileHandModeActive } from '../features/canvas/touch-gestures';
import { exportPresetsJSON } from '../features/canvas/preset-manager';
import * as layoutUI from '../ui/layout-ui';
import * as pagesUI from '../ui/pages-ui';
import * as blockEditorUI from '../ui/block-editor-ui';
import * as presetUI from '../ui/preset-ui';
import * as fontUI from '../ui/font-ui';
import * as settingsUI from '../ui/settings-ui';
import * as previewUI from '../ui/preview-ui';
import * as lorebookUI from '../ui/lorebook-ui';
import * as scriptReviewUI from '../ui/script-review-ui';
import * as qcUI from '../ui/qc-ui';
import * as exportHubUI from '../ui/export-hub-ui';
import * as pipelineOrchestrator from '../features/pipeline/pipeline-orchestrator';
import { changeUILanguage } from './i18n';
import { executeUndo, executeRedo } from './state';
import { updateUndoRedoUI } from '../ui/index';

export function initGlobalBridge(): void {
    if (typeof window === 'undefined') return;

    Object.assign(window, {
        // Pipeline Actions
        openScriptReviewModal: scriptReviewUI.openScriptReviewModal,
        closeScriptReviewModal: scriptReviewUI.closeScriptReviewModal,
        openQcModal: qcUI.openQcModal,
        closeQcModal: qcUI.closeQcModal,
        openExportHubModal: exportHubUI.openExportHubModal,
        closeExportHubModal: exportHubUI.closeExportHubModal,
        runAutoPilotChapterPipeline: pipelineOrchestrator.runAutoPilotChapterPipeline,
        stopAutoPilot: pipelineOrchestrator.stopAutoPilot,

        // UI & Layout
        updateStepperUI: layoutUI.updateStepperUI,
        fitCanvasToScreen: layoutUI.fitCanvasToScreen,
        toggleLeftSidebarMoreMenu: layoutUI.toggleLeftSidebarMoreMenu,
        toggleLeftSidebar: layoutUI.toggleLeftSidebar,
        toggleRightSidebar: layoutUI.toggleRightSidebar,
        openMobileLeftPanel: layoutUI.openMobileLeftPanel,
        openMobileRightPanel: layoutUI.openMobileRightPanel,
        toggleMobileLeftPanel: layoutUI.toggleMobileLeftPanel,
        toggleMobileRightPanel: layoutUI.toggleMobileRightPanel,
        closeMobileMenus: layoutUI.closeMobileMenus,
        toggleMobileMoreMenu: layoutUI.toggleMobileMoreMenu,
        closeMobileMoreMenu: layoutUI.closeMobileMoreMenu,
        navigateMobilePage: layoutUI.navigateMobilePage,
        updateMobileNavUI: layoutUI.updateMobileNavUI,
        openMobileQuickEditor: layoutUI.openMobileQuickEditor,
        closeMobileQuickEditor: layoutUI.closeMobileQuickEditor,
        triggerMobileQuickEdit: layoutUI.triggerMobileQuickEdit,
        changeMobileActiveFontSize: layoutUI.changeMobileActiveFontSize,
        toggleMobileActiveOrientation: layoutUI.toggleMobileActiveOrientation,
        deleteMobileActiveBlock: layoutUI.deleteMobileActiveBlock,
        setRightTab: layoutUI.setRightTab,
        setViewMode: layoutUI.setViewMode,
        changeZoom: layoutUI.changeZoom,
        resetZoom: layoutUI.resetZoom,
        toggleSidebarToolsMenu: layoutUI.toggleSidebarToolsMenu,
        toggleMobileSidebar: layoutUI.toggleMobileSidebar,
        syncMobileMenuState: layoutUI.syncMobileMenuState,
        syncMobileToolbarState: layoutUI.syncMobileToolbarState,
        toggleQuickBilingualMode: layoutUI.toggleQuickBilingualMode,
        toggleQuickAudioDrama: layoutUI.toggleQuickAudioDrama,
        openHelpModal: layoutUI.openHelpModal,
        closeHelpModal: layoutUI.closeHelpModal,
        switchHelpTab: layoutUI.switchHelpTab,

        // Pages Management
        selectPage: pagesUI.selectPage,
        removePage: pagesUI.removePage,
        updatePageListUI: pagesUI.updatePageListUI,
        filterPagesList: pagesUI.filterPagesList,
        toggleExportRangeInputs: pagesUI.toggleExportRangeInputs,
        validateExportRange: pagesUI.validateExportRange,
        setExportRangeToCurrent: pagesUI.setExportRangeToCurrent,
        triggerReplaceBgImage: pagesUI.triggerReplaceBgImage,
        handleReplaceBgFileInput: pagesUI.handleReplaceBgFileInput,
        replacePageBackgroundImage: pagesUI.replacePageBackgroundImage,
        loadDemoManga: pagesUI.loadDemoManga,

        // Block Editor & Styling
        setBlockType: blockEditorUI.setBlockType,
        updateImageBlockOpacity: blockEditorUI.updateImageBlockOpacity,
        updateImageBlockFit: blockEditorUI.updateImageBlockFit,
        updateImageBlockBorderRadius: blockEditorUI.updateImageBlockBorderRadius,
        toggleGradientEnabled: blockEditorUI.toggleGradientEnabled,
        syncGradientStartHex: blockEditorUI.syncGradientStartHex,
        syncGradientEndHex: blockEditorUI.syncGradientEndHex,
        updateGradientAngle: blockEditorUI.updateGradientAngle,
        restoreBackgroundForBlock: blockEditorUI.restoreBackgroundForBlock,
        restoreOriginalBackground: blockEditorUI.restoreOriginalBackground,
        syncTextColorHex: blockEditorUI.syncTextColorHex,
        syncBgColorHex: blockEditorUI.syncBgColorHex,
        syncStrokeColorHex: blockEditorUI.syncStrokeColorHex,
        syncShadowColorHex: blockEditorUI.syncShadowColorHex,
        setBilingualMode: blockEditorUI.setBilingualMode,
        setActiveBlockGender: blockEditorUI.setActiveBlockGender,
        insertRichTextTag: blockEditorUI.insertRichTextTag,
        applyRichColorToSelection: blockEditorUI.applyRichColorToSelection,
        applyRichSizeToSelection: blockEditorUI.applyRichSizeToSelection,
        clearRichFormattingFromSelection: blockEditorUI.clearRichFormattingFromSelection,

        // Canvas & Transformations
        toggleBlockAutoFit: canvasService.toggleBlockAutoFit,
        toggleAutoFit: canvasService.toggleAutoFit,
        applyStylePreset: canvasService.applyStylePreset,
        updateSfxSkewX: canvasService.updateSfxSkewX,
        updateSfxSkewY: canvasService.updateSfxSkewY,
        updateSfxWave: canvasService.updateSfxWave,
        updateSfxBulge: canvasService.updateSfxBulge,
        updateSfxArc: canvasService.updateSfxArc,
        updateSfxRotate: canvasService.updateSfxRotate,
        updateTextRotate: canvasService.updateTextRotate,
        updateTextOffsetX: canvasService.updateTextOffsetX,
        updateTextOffsetY: canvasService.updateTextOffsetY,
        nudgeTextOffset: canvasService.nudgeTextOffset,
        resetTextOffset: canvasService.resetTextOffset,
        resetWarpTransformControls: canvasService.resetWarpTransformControls,
        resetSfxAngleControls: canvasService.resetSfxAngleControls,
        toggleActiveBlockBold: canvasService.toggleActiveBlockBold,
        toggleActiveBlockItalic: canvasService.toggleActiveBlockItalic,
        toggleActiveBlockUnderline: canvasService.toggleActiveBlockUnderline,
        setActiveBlockTextTransform: canvasService.setActiveBlockTextTransform,
        updateLineHeight: canvasService.updateLineHeight,
        updateLetterSpacing: canvasService.updateLetterSpacing,
        updateStrokeWidth2: canvasService.updateStrokeWidth2,
        syncStrokeColor2Hex: canvasService.syncStrokeColor2Hex,
        updateShadowOffsetX: canvasService.updateShadowOffsetX,
        updateShadowOffsetY: canvasService.updateShadowOffsetY,
        cleanActiveBlockPunctuation: canvasService.cleanActiveBlockPunctuation,
        cleanAllBlocksPunctuation: canvasService.cleanAllBlocksPunctuation,
        applyCurrentStyleToPage: canvasService.applyCurrentStyleToPage,
        applyCurrentStyleToAllPages: canvasService.applyCurrentStyleToAllPages,
        alignActiveBlockPosition: canvasService.alignActiveBlockPosition,
        toggleSelectedBlocksOrientation: canvasService.toggleSelectedBlocksOrientation,
        normalizeAllBlocksToHorizontal: canvasService.normalizeAllBlocksToHorizontal,
        duplicateActiveBlock: canvasService.duplicateActiveBlock,
        toggleActiveBlockOrientation: canvasService.toggleActiveBlockOrientation,
        addNewBlock: canvasService.addNewBlock,
        toggleNumberingMode: canvasService.toggleNumberingMode,
        startNumberingMode: canvasService.startNumberingMode,
        finishNumberingMode: canvasService.finishNumberingMode,
        cancelNumberingMode: canvasService.cancelNumberingMode,
        applyMangaSortToActivePage: canvasService.applyMangaSortToActivePage,
        applyManhwaSortToActivePage: canvasService.applyManhwaSortToActivePage,
        moveBlockOrder: canvasService.moveBlockOrder,
        setBlockOrderIndex: canvasService.setBlockOrderIndex,
        triggerAddImageBlock: canvasService.triggerAddImageBlock,
        handleImageBlockSelect: canvasService.handleImageBlockSelect,
        triggerReplaceImageBlock: canvasService.triggerReplaceImageBlock,
        handleReplaceImageBlockSelect: canvasService.handleReplaceImageBlockSelect,
        deleteActiveBlock: canvasService.deleteActiveBlock,
        selectBlock: canvasService.selectBlock,
        selectAllBlocksOnPage: canvasService.selectAllBlocksOnPage,
        syncActiveBlockStyle: canvasService.syncActiveBlockStyle,
        syncActiveBlockTranslation: canvasService.syncActiveBlockTranslation,
        copyBlockStyle: canvasService.copyBlockStyle,
        pasteBlockStyle: canvasService.pasteBlockStyle,
        navigateBlocks: canvasService.navigateBlocks,
        autoMatchActiveBlockStyle: canvasService.autoMatchActiveBlockStyle,
        autoMatchBlockStyle: canvasService.autoMatchBlockStyle,
        toggleMagicWandMode: canvasService.toggleMagicWandMode,
        autoSnapActiveBlockToUnderlyingBubble: canvasService.autoSnapActiveBlockToUnderlyingBubble,
        autoSnapSelectedBlocksToBubbles: canvasService.autoSnapSelectedBlocksToBubbles,
        triggerInlineEditActiveBlock: canvasService.triggerInlineEditActiveBlock,
        commitActiveEditingState: canvasService.commitActiveEditingState,
        toggleMobileHandMode,
        isMobileHandModeActive,

        // Settings & Modals
        openSettingsModal: settingsUI.openSettingsModal,
        closeSettingsModal: settingsUI.closeSettingsModal,
        switchSettingsTab: settingsUI.switchSettingsTab,
        toggleApiKeyVisibility: settingsUI.toggleApiKeyVisibility,
        fetchGeminiModels: settingsUI.fetchGeminiModels,
        togglePreserveNames: settingsUI.togglePreserveNames,
        saveTranslationGenrePresets: settingsUI.saveTranslationGenrePresets,
        syncGenrePresetCheckboxes: settingsUI.syncGenrePresetCheckboxes,
        updateSelectedModel: settingsUI.updateSelectedModel,
        updateDefaultFont: settingsUI.updateDefaultFont,
        updateDefaultTypeFont: settingsUI.updateDefaultTypeFont,
        updateDefaultFontSize: settingsUI.updateDefaultFontSize,
        updateDefaultLineHeight: settingsUI.updateDefaultLineHeight,
        updateDefaultLetterSpacing: settingsUI.updateDefaultLetterSpacing,
        resetDefaultFontMetrics: settingsUI.resetDefaultFontMetrics,
        onTypographyTargetFontChange: settingsUI.onTypographyTargetFontChange,
        updateSourceLanguage: settingsUI.updateSourceLanguage,
        updateTargetLanguage: settingsUI.updateTargetLanguage,
        updatePronounMatrix: settingsUI.updatePronounMatrix,
        updateGlossary: settingsUI.updateGlossary,
        updateTranslationGenrePreset: settingsUI.updateTranslationGenrePreset,
        updateComicUniverse: settingsUI.updateComicUniverse,
        updateComicGenre: settingsUI.updateComicGenre,
        toggleComicGenre: settingsUI.toggleComicGenre,
        updateComicTone: settingsUI.updateComicTone,
        updateTranslationContextPrompt: settingsUI.updateTranslationContextPrompt,
        updateApiDelay: settingsUI.updateApiDelay,
        updateMaxRetries: settingsUI.updateMaxRetries,
        updateAiProvider: settingsUI.updateAiProvider,
        updateApiEndpoint: settingsUI.updateApiEndpoint,
        updateExportFormat: settingsUI.updateExportFormat,
        updateExportPdfQuality: settingsUI.updateExportPdfQuality,
        updateExportEngine: settingsUI.updateExportEngine,
        updatePipelineMode: settingsUI.updatePipelineMode,
        updateOcrModel: settingsUI.updateOcrModel,
        updateTranslationModel: settingsUI.updateTranslationModel,
        updateAllModelDropdowns: settingsUI.updateAllModelDropdowns,
        toggleAdvancedAiSettings: settingsUI.toggleAdvancedAiSettings,


        // Presets UI
        renderCustomPresetsUI: presetUI.renderCustomPresetsUI,
        renderQuickPresetsBar: presetUI.renderQuickPresetsBar,
        applyCustomPresetUI: presetUI.applyCustomPresetUI,
        savePresetFromActiveBlockUI: presetUI.savePresetFromActiveBlockUI,
        updatePresetFromActiveBlockUI: presetUI.updatePresetFromActiveBlockUI,
        duplicatePresetUI: presetUI.duplicatePresetUI,
        deletePresetUI: presetUI.deletePresetUI,
        openPresetModal: presetUI.openPresetModal,
        closePresetModal: presetUI.closePresetModal,
        selectPresetIconEmoji: presetUI.selectPresetIconEmoji,
        submitPresetModal: presetUI.submitPresetModal,
        triggerImportPresetsFile: presetUI.triggerImportPresetsFile,
        clearAllPresetsWithConfirm: presetUI.clearAllPresetsWithConfirm,
        exportPresetsJSON: exportPresetsJSON,

        // Fonts
        populateCustomFontsDropdown: fontUI.populateCustomFontsDropdown,
        registerCustomFont: fontUI.registerCustomFont,
        uploadCustomFonts: fontUI.uploadCustomFonts,
        deleteCustomFont: fontUI.deleteCustomFont,
        deleteAllCustomFonts: fontUI.deleteAllCustomFonts,
        renderCustomFontsListUI: fontUI.renderCustomFontsListUI,
        onSearchCustomFonts: fontUI.onSearchCustomFonts,
        loadMoreCustomFonts: fontUI.loadMoreCustomFonts,
        initFontLivePreviewPicker: fontUI.initFontLivePreviewPicker,
        updateFontPickerDisplay: fontUI.updateFontPickerDisplay,
        closeFontPickerDropdown: fontUI.closeFontPickerDropdown,

        // Inpainting & Eraser
        autoCleanActiveBlock: inpainting.autoCleanActiveBlock,
        toggleEraserMode: inpainting.toggleEraserMode,
        openEraserMode: inpainting.openEraserMode,
        closeEraserMode: inpainting.closeEraserMode,
        updateEraserBrushSize: inpainting.updateEraserBrushSize,
        setEraserColor: inpainting.setEraserColor,
        clearEraserDrawing: inpainting.clearEraserDrawing,
        aiSmartInpaintBlock: inpainting.aiSmartInpaintBlock,
        activateEyedropper: inpainting.activateEyedropper,
        setEraserBrushMode: inpainting.setEraserBrushMode,
        startTexturePatchSelection: inpainting.startTexturePatchSelection,
        clearLassoSelection: inpainting.clearLassoSelection,
        runLassoContentAwareFill: inpainting.runLassoContentAwareFill,
        runLassoPatternFill: inpainting.runLassoPatternFill,
        setLassoFillTab: inpainting.setLassoFillTab,
        setLassoFillTechnique: inpainting.setLassoFillTechnique,
        setLassoPatternType: inpainting.setLassoPatternType,
        setLassoPatternOffsetX: inpainting.setLassoPatternOffsetX,
        setLassoPatternOffsetY: inpainting.setLassoPatternOffsetY,
        nudgeLassoPatternOffset: inpainting.nudgeLassoPatternOffset,
        resetLassoPatternOffset: inpainting.resetLassoPatternOffset,
        renderActiveLassoPreview: inpainting.renderActiveLassoPreview,
        pickLassoSamplePatch: inpainting.pickLassoSamplePatch,
        pickLassoRectSample: inpainting.pickLassoRectSample,
        autoSampleNearbyLassoRect: inpainting.autoSampleNearbyLassoRect,
        minimizeEraserPanel: inpainting.minimizeEraserPanel,
        expandEraserPanel: inpainting.expandEraserPanel,

        // IO, Import, Export & GDrive
        handleUploadedFiles: io.handleUploadedFiles,
        sortPagesByName: io.sortPagesByName,
        exportActivePage: io.exportActivePage,
        closeExportModal: io.closeExportModal,
        runBatchExport: io.runBatchExport,
        runPdfExport: io.runPdfExport,
        promptExportScript: io.promptExportScript,
        exportTranslationScript: io.exportTranslationScript,
        importTranslationScript: io.importTranslationScript,
        triggerImportScript: io.triggerImportScript,
        exportProjectBackup: io.exportProjectBackup,
        importProjectBackup: io.importProjectBackup,
        clearCurrentProject: io.clearCurrentProject,
        openFindReplaceModal: io.openFindReplaceModal,
        closeFindReplaceModal: io.closeFindReplaceModal,
        executeFindReplaceAll: io.executeFindReplaceAll,
        exportCurrentPagePSD: io.exportCurrentPagePSD,
        openGDriveModal: gdrive.openGDriveModal,
        closeGDriveModal: gdrive.closeGDriveModal,
        saveGDriveTokenFromUI: gdrive.saveGDriveTokenFromUI,
        loginWithGoogleOAuth: gdrive.loginWithGoogleOAuth,
        uploadProjectToGDrive: gdrive.uploadProjectToGDrive,
        uploadActivePageToGDrive: gdrive.uploadActivePageToGDrive,
        uploadBatchPagesToGDrive: gdrive.uploadBatchPagesToGDrive,
        saveGDriveClientIdFromUI: gdrive.saveGDriveClientIdFromUI,
        logoutGDrive: gdrive.logoutGDrive,
        openSelectedFolderOnGDrive: gdrive.openSelectedFolderOnGDrive,
        importProjectFromGDrive: gdrive.importProjectFromGDrive,
        loadGDriveProjectList: gdrive.loadGDriveProjectList,
        createNewGDriveFolder: gdrive.createNewGDriveFolder,
        onGDriveFolderChange: gdrive.onGDriveFolderChange,
        loadGDriveFolders: gdrive.loadGDriveFolders,
        promptGDriveFolderLink: gdrive.promptGDriveFolderLink,

        // File System Direct Access
        openLocalFolderPicker: fsAccess.openLocalFolderPicker,
        exportPagesDirectlyToDisk: fsAccess.exportPagesDirectlyToDisk,
        saveProjectDirectlyToDisk: fsAccess.saveProjectDirectlyToDisk,
        reconnectDirectoryHandle: fsAccess.reconnectDirectoryHandle,
        unlinkConnectedFolder: fsAccess.unlinkConnectedFolder,

        // AI Services & Memory
        toggleStoryMemory: aiService.toggleStoryMemory,
        clearStoryMemory: aiService.clearStoryMemory,
        viewStoryMemoryModal: aiService.viewStoryMemoryModal,
        cancelBatchTranslation: aiService.cancelBatchTranslation,
        translateActivePage: aiService.translateActivePage,
        runBatchTranslation: aiService.runBatchTranslation,
        requestAiInpaintPatch: aiService.requestAiInpaintPatch,
        runAIEraseTextPage: aiService.runAIEraseTextPage,

        // Audio Drama & TTS
        playPageAudioDrama: audio.playPageAudioDrama,
        pauseAudioDrama: audio.pauseAudioDrama,
        stopAudioDrama: audio.stopAudioDrama,
        speakActiveBlock: audio.speakActiveBlock,
        testVoice: audio.testVoice,
        openAudioSettingsModal: audio.openAudioSettingsModal,
        closeAudioSettingsModal: audio.closeAudioSettingsModal,
        updateAudioSettingsFromUI: audio.updateAudioSettingsFromUI,

        // TOEIC & Pronouns
        quickOpenToeicAnalysis: toeic.quickOpenToeicAnalysis,
        updateToeicTabUI: toeic.updateToeicTabUI,
        resetToeicAnalysisUI: toeic.resetToeicAnalysisUI,
        displayToeicAnalysis: toeic.displayToeicAnalysis,
        checkToeicAnswer: toeic.checkToeicAnswer,
        analyzeBlockForToeic: toeic.analyzeBlockForToeic,
        toggleSaveToeicWordByIndex: toeic.toggleSaveToeicWordByIndex,
        updateToeicNotebookUI: toeic.updateToeicNotebookUI,
        openSrsReviewModal: toeic.openSrsReviewModal,
        closeSrsReviewModal: toeic.closeSrsReviewModal,
        flipSrsCard: toeic.flipSrsCard,
        speakSrsCurrentWord: toeic.speakSrsCurrentWord,
        submitSrsReview: toeic.submitSrsReview,
        deleteSavedToeicWord: toeic.deleteSavedToeicWord,
        exportToeicWordsToAnki: toeic.exportToeicWordsToAnki,
        speakText: toeic.speakText,
        setToeicMode: toeic.setToeicMode,
        showToeicRecallHint: toeic.showToeicRecallHint,
        checkToeicRecall: toeic.checkToeicRecall,
        speakCorrectRecallSentence: toeic.speakCorrectRecallSentence,
        selectToeicQuestion: toeic.selectToeicQuestion,
        renderActiveToeicQuestion: toeic.renderActiveToeicQuestion,
        addCharacterToMatrix: pronoun.addCharacterToMatrix,
        removeCharacterFromMatrix: pronoun.removeCharacterFromMatrix,
        updateRelationship: pronoun.updateRelationship,

        // Lorebook & Character Dossier
        openLorebookModal: lorebookUI.openLorebookModal,
        closeLorebookModal: lorebookUI.closeLorebookModal,
        switchLorebookTab: lorebookUI.switchLorebookTab,
        renderCharacterDossierUI: lorebookUI.renderCharacterDossierUI,
        addCharacterDossierEntry: lorebookUI.addCharacterDossierEntry,
        removeCharacterDossierEntry: lorebookUI.removeCharacterDossierEntry,
        renderLorebookUI: lorebookUI.renderLorebookUI,
        addLorebookTermEntry: lorebookUI.addLorebookTermEntry,
        removeLorebookTermEntry: lorebookUI.removeLorebookTermEntry,
        exportLorebookJSON: lorebookUI.exportLorebookJSON,
        importLorebookJSON: lorebookUI.importLorebookJSON,

        // Preview & Export Preview Mode
        openPreviewMode: previewUI.openPreviewMode,
        openExportZipPreview: previewUI.openExportZipPreview,
        openExportPdfPreview: previewUI.openExportPdfPreview,
        closePreviewMode: previewUI.closePreviewMode,
        previewPrevPage: previewUI.previewPrevPage,
        previewNextPage: previewUI.previewNextPage,
        previewJumpToPage: previewUI.previewJumpToPage,
        setPreviewViewMode: previewUI.setPreviewViewMode,
        setPreviewFitMode: previewUI.setPreviewFitMode,
        togglePreviewFitMode: previewUI.togglePreviewFitMode,
        applySinglePageFitAndZoom: previewUI.applySinglePageFitAndZoom,
        setPreviewZoom: previewUI.setPreviewZoom,
        changePreviewZoom: previewUI.changePreviewZoom,
        resetPreviewZoom: previewUI.resetPreviewZoom,
        togglePageExportSelection: previewUI.togglePageExportSelection,
        selectAllExportPages: previewUI.selectAllExportPages,
        deselectAllExportPages: previewUI.deselectAllExportPages,
        switchPreviewExportTab: previewUI.switchPreviewExportTab,
        executeZipExportFromPreview: previewUI.executeZipExportFromPreview,
        executePdfExportFromPreview: previewUI.executePdfExportFromPreview,
        executeGDriveExportFromPreview: previewUI.executeGDriveExportFromPreview,
        executeSinglePageExportFromPreview: previewUI.executeSinglePageExportFromPreview,
        copyPreviewPageToClipboard: previewUI.copyPreviewPageToClipboard,
        renderPreviewViewport: previewUI.renderPreviewViewport,
        renderPreviewPage: previewUI.renderPreviewViewport,
        toggleExportModalFit: io.toggleExportModalFit,

        // Core State & Utilities
        executeUndo,
        executeRedo,
        updateUndoRedoUI,
        changeUILanguage
    });
}
